workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic_app_store_connect
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.illuminations.contemplations
      vars:
        BUNDLE_ID: "com.illuminations.contemplations"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Prepare web assets
        script: |
          # Créer le dossier dist s'il n'existe pas
          mkdir -p dist
          
          # Copier index.html
          cp index.html dist/
          
          # Copier dossier assets s'il existe
          if [ -d "assets" ]; then
            cp -r assets dist/
          fi
          
          # Copier dossier static s'il existe (pour les apps Python)
          if [ -d "static" ]; then
            cp -r static dist/
          fi
          
          # Afficher le contenu pour debug
          echo "Contenu du dossier dist:"
          ls -la dist/
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - paul.todorov.mail@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false