workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: personal  # OBLIGATOIRE pour TestFlight
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.illuminations.contemplations
      vars:
        BUNDLE_ID: "com.illuminations.contemplations"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"  # Capacitor utilise "App" par défaut
        XCODE_SCHEME: "App"  # Capacitor utilise "App" par défaut
        APP_ID: 1234567890  # Votre App Store Connect App ID (à obtenir)
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios/App
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1))
          agvtool new-version -all $BUILD_NUMBER
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - paul.todorov.mail@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration  # Utilise l'intégration configurée
        submit_to_testflight: true
        submit_to_app_store: false