workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.illuminations.contemplations
      vars:
        BUNDLE_ID: "com.illuminations.contemplations"
        XCODE_WORKSPACE: "ios/WordGenerator.xcworkspace"
        XCODE_SCHEME: "WordGenerator"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Bundle ID
        script: |
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = com.illuminations.contemplations;/g' ios/WordGenerator.xcodeproj/project.pbxproj
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - votre-email@example.com
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false