workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: personal
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.illuminations.contemplations
      vars:
        XCODE_WORKSPACE: "ios/WordGenerator.xcworkspace"
        XCODE_SCHEME: "WordGenerator"
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Auto-increment version and build number
        script: |
          cd ios
          # Set build number to current timestamp (always unique)
          agvtool new-version -all $(date +%s)
          # Set version to 1.1 (you can change this as needed)
          agvtool new-marketing-version "1.1"
          cd ..
      - name: Set Bundle ID and Provisioning Profile
        script: |
          # Mettre à jour le Bundle ID dans le projet
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = com.illuminations.contemplations;/g' ios/WordGenerator.xcodeproj/project.pbxproj
          
          # Forcer Manual Code Signing
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/WordGenerator.xcodeproj/project.pbxproj
          
          # Utiliser les profils
          xcode-project use-profiles
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - paul.todorov.mail@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false