workflows:
  ios-test:
    name: iOS Test Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
    artifacts:
      - build/ios/ipa/*.ipa